// <auto-generated />
using InterviewAPI2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InterviewAPI2.Migrations
{
    [DbContext(typeof(BookDBContext))]
    partial class BookDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InterviewAPI2.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AuthorName = "Joseph Murphy",
                            Name = "The Power of Your Mind"
                        },
                        new
                        {
                            id = 2,
                            AuthorName = "Sri M",
                            Name = "Sri M: The Journey Continues"
                        },
                        new
                        {
                            id = 3,
                            AuthorName = "Sri M",
                            Name = "Apprenticed To A Himalayan Master"
                        },
                        new
                        {
                            id = 4,
                            AuthorName = "Shivram Karanth",
                            Name = "Mukajjiya Kanasugalu"
                        },
                        new
                        {
                            id = 5,
                            AuthorName = "PoornaChandra Tejasvi",
                            Name = "Karvalo"
                        },
                        new
                        {
                            id = 6,
                            AuthorName = "Paramahamsa Yogananda",
                            Name = "AutoBiography of A Yogi"
                        },
                        new
                        {
                            id = 7,
                            AuthorName = "Chetan Bhagat",
                            Name = "A Night At A Call Center"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
